# Generated by Django 4.0.5 on 2022-08-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anti_d_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='localgovernment',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
