# Generated by Django 4.0.5 on 2022-08-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anti_d_app', '0004_report_content_report_disaster_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='hearing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ヒアリング日時'),
        ),
        migrations.AddField(
            model_name='report',
            name='related_organization',
            field=models.ManyToManyField(to='anti_d_app.relatedorganization'),
        ),
    ]
